### ISSUE TITLE
Is Spigot required?

### ISSUE THREAD

**Issue by allanonmage** [MagmaGuy/BetterStructures#20]
Spigot's website always displays a white page for me, so idk what your page might say about your software.  Can I use this with a Fabric server, or only Spigot?

I would like to import cool structures from Patreon memberships into my world.

I came across your software on this video: https://www.youtube.com/watch?v=bK3ATUFxSrA

**Comment by MagmaGuy** [comment]
It is made for spigot/paper, it is untested for fabric and I have no intention of doing any kind of specific support for it.
